# Travis CI setup for checking OpenFOAM code compiles and more or less
# complies with the style rules

sudo: required
dist: trusty
language: cpp

before_install:
    - sudo add-apt-repository http://dl.openfoam.org/ubuntu
    - sudo sh -c "wget -O - http://dl.openfoam.org/gpg.key | apt-key add -"
    - sudo apt-get update -qq
    - sudo apt-get install -qq openfoam4
    - sudo apt-get install -qq vera++

install:
    - source /opt/openfoam4/etc/bashrc
    - wmake libso

script:
    - source /opt/openfoam4/etc/bashrc
    - ./foamStyleCheck/checkStyle
